version: '3.8'

services:
  storage-system:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - FIREBASE_API_KEY=${FIREBASE_API_KEY}
        - FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
        - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
        - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
        - FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
        - FIREBASE_APP_ID=${FIREBASE_APP_ID}
        - FIREBASE_ADMIN_SDK_KEY=${FIREBASE_ADMIN_SDK_KEY}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
      - FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
      - FIREBASE_APP_ID=${FIREBASE_APP_ID}
      - FIREBASE_ADMIN_SDK_KEY=${FIREBASE_ADMIN_SDK_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
